# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Get tags
        id: get-tags
        run: echo "::set-output name=tags::$(git tag -l)"
        
      - name: Find latest tag
        id: latest-tag
        run: |
         TAGS=${{ steps.get-tags.outputs.tags }}
         TAG_LIST=(${TAGS// / })
         LATEST_TAG=${TAG_LIST[${#TAG_LIST[@]} - 1]}
         echo "::set-output name=latest_tag::${LATEST_TAG}"

      - name: Display latest tag
        run: echo "Latest tag is ${{ steps.latest-tag.outputs.latest_tag }}"         
