name: Auto Tag and Identify PR

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed

jobs:
  tag_and_identify:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
         fetch-depth: 0

    - name: Determine issue type
      id: determine-type
      run: |
          issue_type=$(git log --format=%B -n 1 ${{ github.event.before }}..${{ github.event.after }} | grep -Eo '^(feat|fix|doc|refactor)')
          echo "Issue type: $issue_type"
          echo "::set-output name=issue_type::$issue_type"     
          echo "$issue_type"
    
    - name: Identify PR Type and Tag Repository
      id: tag_and_identify
      env:
       GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        # Use GitHub API to get the PR details
        PR_NUMBER=$(echo "${{ github.event.pull_request.url }}" | awk -F'/' '{print $NF}')
        PR_DETAILS=$(curl -s -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
                      "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER")

        echo "$PR_TITLE"
        # Extract issue type from PR title
        PR_TITLE=$(echo "$PR_DETAILS" | jq -r '.title')
        echo "$PR_TITLE"
        if echo "$PR_TITLE" | grep -qiE 'feat'; then
          ISSUE_TYPE="feat"
        elif echo "$PR_TITLE" | grep -qiE 'fix'; then
          ISSUE_TYPE="Fix"
        else
          ISSUE_TYPE="Other"
        fi
        
        echo "$ISSUE_TYPE"
        echo "::set-output name=issue_type::$ISSUE_TYPE"
       
      
    outputs:
      issue_type: ${{ steps.tag_and_identify.outputs.issue_type }}
