name: PR Bumper Commit Handling

on:
  pull_request:
    types:
      - closed

jobs:
  handle_bumper_commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
         fetch-depth: 0

      - name: Extract and process bumper commits
        run: |
          if [[ "${{ github.event.pull_request.merged }}" == "true" && "${{ github.event.pull_request.base.ref }}" == "main" ]]; then
            git log --pretty=format:%s ${GITHUB_REF/refs\/pull\//...}..HEAD | grep -E 'feat|fix|test|style|doc' | while read -r line; do
              echo "Processing commit: $line"
              echo "$line"
              # Add your logic to handle each commit type here
            done
          fi
