name: Analyze Bump Commit

on:
  push:
    branches:
      - main

jobs:
  analyze_bump_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
         fetch-depth: 0

      - name: Extract bump commit message
        id: extract_bump
        run: |
          BUMP_COMMIT_MESSAGE=$(git log -1 --pretty=format:%s ${{ github.sha }} | grep -E '^(feat|fix|test|style|doc):')
          echo "Bump Commit Message: $BUMP_COMMIT_MESSAGE"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_SHA: ${{ github.sha }}

      - name: Print conventional commit message
        run: |
          if [[ -n "$BUMP_COMMIT_MESSAGE" ]]; then
            echo "Conventional Commit Message: $BUMP_COMMIT_MESSAGE"
            # You can use $BUMP_COMMIT_MESSAGE for further actions or logic
          else
            echo "No bump commit found."
          fi
