name: Auto Tag and Identify PR

on:
  pull_request:
    types:
      - closed

jobs:
  tag_and_identify:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Identify PR Type and Tag Repository
      id: tag_and_identify
      run: |
        # Use GitHub API to get the PR details
        PR_NUMBER=$(echo "${{ github.event.pull_request.url }}" | awk -F'/' '{print $NF}')
        PR_DETAILS=$(curl -s -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
                      "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER")
        
        # Extract issue type from PR title
        PR_TITLE=$(echo "$PR_DETAILS" | jq -r '.title')
        if echo "$PR_TITLE" | grep -qiE 'bug|fix'; then
          ISSUE_TYPE="Bug"
        elif echo "$PR_TITLE" | grep -qiE 'feature|enhance'; then
          ISSUE_TYPE="Feature"
        else
          ISSUE_TYPE="Other"
        fi
        
        # Tag the repository with the identified issue type
        git tag "$ISSUE_TYPE" -m "Tagged as $ISSUE_TYPE issue" || true
        git push origin "$ISSUE_TYPE" || true
        
        echo "::set-output name=issue_type::$ISSUE_TYPE"
        
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      
    outputs:
      issue_type: ${{ steps.tag_and_identify.outputs.issue_type }}
